config/routes.rb
Battleships::Application.routes.draw do
  resources :blocks

  resources :game_ships

  resources :nukes

  resources :ships

  resources :games do
    get :register, :on => :member
    post :nuke, :on => :member
    get :battle, :on => :member
  end

  root :to => "public#home"
end

app/models/nuke.rb
class Nuke < ActiveRecord::Base
  belongs_to :game
  validates :game_id, :presence => true
  validates :x, :presence => true, :numericality => true
  validates :y, :presence => true, :numericality => true

  attr_accessor :json_data
  attr_accessor :response_data

  after_create :check_blocks

  def check_blocks

    self.json_data = ({"id"=>Integer(self.game.server_game_id), "x"=>Integer(self.x), "y"=> Integer(self.y)}).to_json
    if self.server_nuke_boolean?
      if block = Block.where(:x => self.x, :y => self.y, :server_board => false).last

        if block.game_ship


          if block.state == "in_play"
            game_ship = GameShip.find(block.game_ship_id)
            
            game_ship.hit_count += 1
            game_ship.check_if_ship_is_sunk
            game = self.game
            game.server_hits += 1
            game.save

          end
          block.hit_block!


          self.update_attributes(:status => "hit")
        else

          block.miss_block!
          self.update_attributes(:status => "miss")
        end
      end
    else
      if block = Block.where(:x => self.x, :y => self.y, :server_board => true).last
        if self.status == "hit"
          if block.state == "in_play"
            game = self.game
            game.client_hits += 1
            game.save

          end
          block.hit_block!
        else

          block.miss_block!
        end

      end
    end
  end


  after_find do |nuke|
    game = nuke.game

    nuke.json_data = ({"id"=>Integer(game.server_game_id), "x"=>Integer(nuke.x), "y"=> Integer(nuke.y)}).to_json
  end

  def send_nuke_to_server(url)
    p self.json_data
    uri = URI.parse(url)

      request = Net::HTTP::Post.new(uri.request_uri,  initheader = {'Content-Type' =>'application/json'})
      request.body = self.json_data
      response = Net::HTTP.new(uri.host, uri.port).start {|http| http.request(request) }

      return data = ActiveSupport::JSON.decode(response.body)
  end
end

app/controllers/nukes_controller.rb
require 'net/http'
require 'rubygems'
require 'json'
class NukesController < ApplicationController

  def create

    @nuke = Nuke.create(params[:nuke])
    @game = @nuke.game
    @json_string= @nuke.json_data
   
    if @nuke.valid?
      data = @nuke.send_nuke_to_server("http://battle.platform45.com/nuke")
      p data

      @nuke.update_attributes(:status => data["status"])

      @server_nuke = Nuke.create(:game_id => @game.id, :server_nuke_boolean => true, :x =>Integer(data["x"]), :y => Integer(data["y"]))
      if data["sunk"]
        @server_ship = ServerShip.create(:name => data["sunk"], :sunk => true, :game_id => @game.id)
      end

      if data["game_status"]
        if data["game_status"] == "lost"
          @game.win_game!

            render :won_game

        else
          @game.lose_game
          render :lost_game 
        end
      end
      render :battle
    else
      render :template => "nukes/errors.js.erb"
    end
  end


end

app/helpers/nukes_helper.rb
module NukesHelper
end

app/views/nukes/_form.html.haml
= form_for @nuke do |f|
  -if @nuke.errors.any?
    #error_explanation
      %strong= "#{pluralize(@nuke.errors.count, "error")} prohibited this nuke from being saved:"
      %ol
        - @nuke.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit

app/views/nukes/battle.js.erb
$("#content").html("<%= escape_javascript(render(:partial => "games/battle", :locals => {:game => @game})) %>")

app/views/nukes/edit.html.haml
%h1 Editing nuke
%p
  = link_to 'Back', :back

= render 'form'

app/views/nukes/index.html.haml
%h1 Listing nukes
%p
  = link_to 'New Nuke', new_nuke_path
  |
  = link_to "Back", :back      
%table.dataTable
  %tr
    %th
    %th


  - @nukes.each do |nuke|
    %tr

      %td= link_to 'Edit', edit_nuke_path(nuke)
      %td= link_to 'Destroy', nuke, :confirm => 'Are you sure?', :method => :delete

%br

app/views/nukes/lost_game.js.erb
$("#content").html("<%= escape_javascript(render(:partial => "games/lost_game", :locals => {:game => @game})) %>")

app/views/nukes/new.html.haml
%h1 New nuke
%p
  = link_to 'Back', :back

= render 'form'

app/views/nukes/show.html.haml
%h1 nuke
%p
  = link_to 'Edit', edit_nuke_path(@nuke)
  |
  = link_to 'Back', :back

app/views/nukes/won_game.js.erb
$("#content").html("<%= escape_javascript(render(:partial => "games/won_game", :locals => {:game => @game})) %>")