config/routes.rb
Battleships::Application.routes.draw do
  resources :blocks

  resources :game_ships

  resources :nukes

  resources :ships

  resources :games do
    get :register, :on => :member
    post :nuke, :on => :member
    get :battle, :on => :member
  end

  root :to => "public#home"
end

app/models/game_ship.rb
class GameShip < ActiveRecord::Base
  belongs_to :ship
  belongs_to :game
  has_many :blocks

  validates :game_id, :presence => true
  validates :ship_id, :presence => true

  before_create :check_for_max_ships
  after_create :update_blocks

  before_destroy :check_blocks

  def check_for_max_ships
    ship = Ship.find(self.ship_id)

    if GameShip.where(:ship_id => ship.id, :game_id => self.game_id).count >= ship.max_per_game
      game = Game.find(self.game_id)
      game.errors.add(:base, "Max Number of ships per game reached")
      return false
    end
  end

  def update_blocks
    Block.where(:game_id => self.game_id, :server_board => false).each do |block|
      self.ship.length.times do |i|
        if self.orientation == "horizontal"

          if block.y == self.y


            if (block.x + i) == (self.x + i)
              block.update_attributes(:game_ship_id => self.id)
              if i != 0
                if next_block =Block.where(:game_id => self.game_id, :server_board => false, :x => block.x + i, :y => block.y).last

                  next_block.update_attributes(:game_ship_id => self.id)
                end
              end
            end
          end
        elsif self.orientation == "vertical"
          if block.x == self.x
            if (block.y + i) == (self.y + i)

              block.update_attributes(:game_ship_id => self.id)
              if i != 0
                if next_block =Block.where(:game_id => self.game_id, :server_board => false, :x => block.x, :y => block.y + i).last

                  next_block.update_attributes(:game_ship_id => self.id)
                end
              end
            end
          end
        end
      end

    end

  end

  def check_if_ship_is_sunk

    if self.sunk == false
      if self.hit_count == self.ship.length
        self.update_attributes(:sunk => true,:hit_count => self.hit_count)

      end
    end
  end

  def check_blocks
    Block.where(:game_id => self.game_id, :server_board => false).each do |block|
      self.ship.length.times do |i|
        if self.orientation == "horizontal"

          if block.y == self.y


            if (block.x + i) == (self.x + i)
              block.update_attributes(:game_ship_id => nil)
              if i != 0
                if next_block =Block.where(:game_id => self.game_id, :server_board => false, :x => block.x + i, :y => block.y).last

                  next_block.update_attributes(:game_ship_id => nil)
                end
              end
            end
          end
        elsif self.orientation == "vertical"
          if block.x == self.x
            if (block.y + i) == (self.y + i)

              block.update_attributes(:game_ship_id => nil)
              if i != 0
                if next_block =Block.where(:game_id => self.game_id, :server_board => false, :x => block.x, :y => block.y + i).last

                  next_block.update_attributes(:game_ship_id => nil)
                end
              end
            end
          end
        end
      end

    end
  end


end

app/controllers/game_ships_controller.rb
class GameShipsController < ApplicationController
  def index
    @game_ships = GameShip.all
  end

  def show
    @game_ship = GameShip.find(params[:id])
  end

  def new
    @game_ship = GameShip.new
  end

  def create
    @game = Game.find(params[:game_ship][:game_id])
    @game_ship = GameShip.create(game_ship_params)
    if @game_ship.valid? 
      render :register
    else
      render :template => "game_ships/errors.js.erb"
    end
  end

  def destroy
    @game_ship = find_game_ship
    @game = @game_ship.game
    if @game_ship.destroy
      render :register
    end
  end

  def edit
    @game_ship = find_game_ship
    @game = @game_ship.game
    render :edit
  end

  def update
    @game_ship = find_game_ship
    @game = @game_ship.game
    if @game_ship.update(game_ship_params)
      render :register
    else
      render :edit
    end
  end

  private

  def find_game_ship
    GameShip.find(params[:id])
  end

  def game_ship_params
    params.require(:game_ship).permit(:game_id, :ship_id, :hit_count, :orientation, :sunk, :x, :y)
  end
end

app/helpers/game_ships_helper.rb
module GameShipsHelper
end

app/views/game_ships/_edit.html.haml
= form_for @game_ship, :remote => true do |f|
  -if @game_ship.errors.any?
    #error_explanation
      %strong= "#{pluralize(@game_ship.errors.count, "error")} prohibited this game_ship from being saved:"
      %ol
        - @game_ship.errors.full_messages.each do |msg|
          %li= msg



  %p.field
    = f.label :orientation
    <br />
    = f.text_field :orientation
  %p.field
    = f.label :x
    <br />
    = f.number_field :x
  %p.field
    = f.label :y
    <br />
    = f.number_field :y
  .actions
    = f.submit

app/views/game_ships/_errors.html.haml
-if @game.errors.any?
  #error_explanation
    %strong= "#{pluralize(@game.errors.count, "error")} prohibited this game from being saved:"
    %ol
      - @game.errors.full_messages.each do |msg|
        %li= msg

app/views/game_ships/_form.html.haml
= form_for @game_ship do |f|
  -if @game_ship.errors.any?
    #error_explanation
      %strong= "#{pluralize(@game_ship.errors.count, "error")} prohibited this game_ship from being saved:"
      %ol
        - @game_ship.errors.full_messages.each do |msg|
          %li= msg

  %p.field
    = f.label :game_id
    <br />    
    = f.number_field :game_id
  %p.field
    = f.label :ship_id
    <br />    
    = f.number_field :ship_id
  %p.field
    = f.label :sunk
    <br />    
    = f.check_box :sunk
  %p.field
    = f.label :hit_count
    <br />    
    = f.number_field :hit_count
  %p.field
    = f.label :orientation
    <br />    
    = f.text_field :orientation
  %p.field
    = f.label :x
    <br />    
    = f.number_field :x
  %p.field
    = f.label :y
    <br />    
    = f.number_field :y
  .actions
    = f.submit

app/views/game_ships/_register.html.haml
-if @game.errors.any?
  #error_explanation
    %strong= "#{pluralize(@game.errors.count, "error")} prohibited this game from being saved:"
    %ol
      - @game.errors.full_messages.each do |msg|
        %li= msg


%h3= "Game Board"
%table
  %tr
    %td
      %table.player_board
        %tr.align_center
          %td.white
          -10.times do |g|
            %td.white
              ="#{g}"
        -10.times do |i|
          %tr.line_one
            %td.white
              ="#{i}"
            -Block.where(:game_id => game.id, :server_board => false, :y => i).order(:x).each do |block|

              %td.player_placement{:id => "player_board_#{block.x}_#{block.y}", :data_x => block.x, :data_y => block.y}
                = "#{block.x}:#{block.y}"


    %td      
      #ships_for_game
        %h3 Ship Details
        %table
          %tr
            %td

              #ships_horizontal
                %h4
                  ="Orientation : Horizontal"
                %table
                  %tr


                    %td

                    -Ship.all.each do |ship|
                      %tr
                        -total_ships_game = GameShip.where(:ship_id => ship.id, :game_id => game.id).count
                        -if total_ships_game < ship.max_per_game
                          %td
                            =ship.name

                          -(ship.max_per_game - total_ships_game).times do |i|
                            %td
                              -if ship.length > 2
                                .ships_horizontal{:id => "ship_#{ship.id}",:style => "width: #{(ship.length * 30) + 15}px;", :ship_id =>ship.id, :orientation => "horizontal", :data_length => ship.length, :game_id => game.id}
                                  &nbsp;
                              -else
                                .ships_horizontal{:id => "ship_#{ship.id}",:style => "width: #{(ship.length * 30)}px;", :ship_id =>ship.id, :orientation => "horizontal", :data_length => ship.length, :game_id => game.id}
                                  &nbsp;
            %td

              #ships_vertical
                %h4
                  ="Orientation : Vertical"
                %table
                  %tr

                    -Ship.all.each do |ship|
                      %td
                        -total_ships_game = GameShip.where(:ship_id => ship.id, :game_id => game.id).count
                        -if total_ships_game < ship.max_per_game
                          %span
                            =ship.name

                          -(ship.max_per_game - total_ships_game).times do |i|
                            %span
                              .ships_vertical{:id => "ship_#{ship.id}",:style => "height: #{(ship.length * 30)}px;", :ship_id =>ship.id, :orientation => "vertical", :data_length => ship.length, :game_id => game.id }
                                &nbsp;
                              %br
      :javascript
        $(function() {
          ShipsDraggables();
          ShipsDroppables();
          draw_ships_for_game();
        });
      %br
%span=link_to "Register Game on Server", register_game_path(game)        
%h3
  Ships In Play
%table.game_ships{:border => 0, :cellpadding => 0, :cellspacing => 0}
  %tr
    %th
      Ship Name
    %th
      x coordinates
    %th
      y coordinates
    %th
      Length
    %th
      Edit
    %th
      Remove
  -GameShip.where(:game_id => game.id).order(:x).each do |game_ship|
    %tr
      %td
        =game_ship.ship.name
      %td
        =game_ship.x
      %td
        =game_ship.y
      %td
        =game_ship.ship.length
      %td
        =link_to "Move Ship", edit_game_ship_path(:id => game_ship.id), :remote => true
      %td
        =link_to "Delete Ship", game_ship_path(:id => game_ship.id), :method => :delete, :remote => true



#json_string{:style => "display:none"}
  =game.json_string




#javascript_data{:style => "display:none"}
  #game_ship_ids
    -game_ship_ids = []
    -GameShip.where(:game_id =>game.id ).each do |game_ship|
      - game_ship_ids << game_ship.id
    =game_ship_ids.join(",")

  #game_ship_x
    -game_ship_x = []
    -GameShip.where(:game_id =>game.id ).each do |game_ship|
      - game_ship_x << game_ship.x
    =game_ship_x.join(",")
  #game_ship_y
    -game_ship_y = []
    -GameShip.where(:game_id =>game.id ).each do |game_ship|
      - game_ship_y << game_ship.y
    =game_ship_y.join(",")

  #game_ship_length
    -game_ship_length = []
    -GameShip.where(:game_id =>game.id ).each do |game_ship|
      - game_ship_length << game_ship.ship.length
    =game_ship_length.join(",")
  #game_ship_orientation
    -game_ship_orientation = []
    -GameShip.where(:game_id =>game.id ).each do |game_ship|
      - game_ship_orientation << game_ship.orientation
    =game_ship_orientation.join(",")



app/views/game_ships/edit.html.haml
%h1 Editing game_ship
%p
  = link_to 'Back', :back

= render 'form'

app/views/game_ships/edit.js.erb
$("#lightbox_content_small").html("<%= escape_javascript(render(:partial => "/game_ships/edit", :locals => {:game_ship => @game_ship}))%>");
$("#lightbox_small").show();


app/views/game_ships/errors.js.erb
$("#lightbox_content_small").html("<%= escape_javascript(render(:partial => "/game_ships/errors", :locals => {:game => @game}))%>");
$("#lightbox_small").show();


app/views/game_ships/index.html.haml
%h1 Listing game_ships
%p
  = link_to 'New Game ship', new_game_ship_path
  |
  = link_to "Back", :back      
%table.dataTable
  %tr
    %th Game
    %th Ship
    %th Sunk
    %th Hit count
    %th Orientation
    %th X
    %th Y
    %th
    %th


  - @game_ships.each do |game_ship|
    %tr
      %td= game_ship.game_id
      %td= game_ship.ship_id
      %td= game_ship.sunk
      %td= game_ship.hit_count
      %td= game_ship.orientation
      %td= game_ship.x
      %td= game_ship.y

      %td= link_to 'Edit', edit_game_ship_path(game_ship)
      %td= link_to 'Destroy', game_ship, :confirm => 'Are you sure?', :method => :delete

%br

app/views/game_ships/new.html.haml
%h1 New game_ship
%p
  = link_to 'Back', :back

= render 'form'

app/views/game_ships/register.js.erb
$("#lightbox_content_small").html("");
$("#lightbox_small").hide();



$("#content").html("<%= escape_javascript(render(:partial => "game_ships/register", :locals => {:game => @game})) %>")

app/views/game_ships/show.html.haml
%h1 game_ship
%p
  = link_to 'Edit', edit_game_ship_path(@game_ship)
  |
  = link_to 'Back', :back

%p
  %b Game
  <br />
  = @game_ship.game_id
%p
  %b Ship
  <br />
  = @game_ship.ship_id
%p
  %b Sunk
  <br />
  = @game_ship.sunk
%p
  %b Hit count
  <br />
  = @game_ship.hit_count
%p
  %b Orientation
  <br />
  = @game_ship.orientation
%p
  %b X
  <br />
  = @game_ship.x
%p
  %b Y
  <br />
  = @game_ship.y