config/routes.rb
Battleships::Application.routes.draw do
  resources :blocks

  resources :game_ships

  resources :nukes

  resources :ships

  resources :games do
    get :register, :on => :member
    post :nuke, :on => :member
    get :battle, :on => :member
  end

  root :to => "public#home"
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :nukes, :dependent => :destroy
  has_many :game_ships, :dependent => :destroy
  has_many :ships, :through => :game_ships
  has_many :blocks, :dependent => :destroy
  validates :email, :presence => true
  validates :name, :presence => true

  attr_accessor :json_string
  after_find do |game|
    game.json_string = ({"name"=>game.name, "email"=>game.email}).to_json
  end

  after_create :create_blocks_for_game

  include Stateflow
  stateflow do
    state_column :status
    initial :in_progress
    state :in_progress, :won, :lost

    event :win_game do
      transitions :from => :in_progress, :to => :won
    end

    event :lose_game do
      transitions :from => :in_progress, :to => :lost
    end
  end

  def create_blocks_for_game
    ## create player_board
    10.times do |x|
      10.times do |y|
        Block.create(:game_id => self.id, :x => x, :y => y, :server_board => false)
      end
    end
    10.times do |x|
      10.times do |y|
        Block.create(:game_id => self.id, :x => x, :y => y, :server_board => true)
      end
    end
  end

  def send_request_to_server(url)
    uri = URI.parse(url)
    request = Net::HTTP::Post.new(uri.request_uri,  initheader = {'Content-Type' =>'application/json'})
    request.body = self.json_string
    response = Net::HTTP.new(uri.host, uri.port).start {|http| http.request(request) }
    return ActiveSupport::JSON.decode(response.body)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = find_game

    flash[:notice] = "Place your ships"
    @game_ships = GameShip.where(:game_id => @game.id)
    render :show
  end

  def register
    @game = Game.find(params[:id])
    @json_string = @game.json_string


    response = @game.send_request_to_server("http://battle.platform45.com/register")
   
    server_game_id = response

    if server_game_id.has_key? "id"
      @game.update_attributes(:server_game_id =>Integer(server_game_id["id"]))
      redirect_to battle_game_path(@game)
    end

  end

  def battle
    @game =Game.find(params[:id])
  end

  #FIXME: THIS IS A TEST
  def new
    @game = Game.new
  end

  def create
    @game = Game.create(game_params)
    if @game.valid?
      redirect_to @game
    else
      render :new
    end
  end

  def nuke
  end

  def edit
    @game = find_game
  end

  def update
    @game = find_game
    if @game.update_attributes(game_params)
      redirect_to games_path
    else
      render :edit
    end
  end

  def destroy
    find_game.destroy

     redirect_to games_path
  end

  private

  def find_game
    Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:email, :name)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_battle.html.haml
%h2 Game
.enemy
  %div{:style => "width: 125px;"}
    %h3= "Enemy's Seas"
  %table.enemy_board

    %tr.align_center
      %td.white
      -10.times do |g|
        %td.white
          ="#{g}"
    -10.times do |i|
      %tr.line_one
        %td.white
          ="#{i}"
        -Block.where(:game_id => game.id, :server_board => true, :y => i).order(:x).each do |block|
          %td.attack_area{:id => "enemy_board_#{block.x}_#{block.y}", :data_x => block.x, :data_y => block.y, :data_game_id => game.id}

.player
  %div{:style => "width: 125px;"}
    %h3= "Player "

  %table.player_board
    %tr.align_center
      %td.white
      -10.times do |g|
        %td.white
          ="#{g}"
    -10.times do |i|
      %tr.line_one
        %td.white
          ="#{i}"
        -Block.where(:game_id => game.id, :server_board => false, :y => i).order(:x).each do |block|

          %td.player_placement{:id => "player_board_#{block.x}_#{block.y}", :data_x => block.x, :data_y => block.y}

  .enemy_sunk_ships
    %h3
      ="Server Ships that have been sunk:"
    
    -ServerShip.where(:game_id => game.id, :sunk=> true).each do |server_ship|
      =server_ship.name
      %br
.ships_show
  %h3 Player Ships
  %table
    %tr
      %th

      %th
    %tr
      %td
        -GameShip.where(:game_id => game.id).order(:ship_id).each do |game_ship|
          -color = "#6d6969"


          -if game_ship.orientation == "vertical"
            -if game_ship.sunk
              -color = "#ff0000"

            =game_ship.ship.name
            %span
              .game_ships_vertical{:id => "game_ship_#{game_ship.id}",:style => "height: #{game_ship.ship.length * 30}px;background-color: #{color}", :game_id => game.id, :orientation => "vertical"}
                &nbsp;
      %td
        -GameShip.where(:game_id => game.id).order(:ship_id).each do |game_ship|
          -color = "#6d6969"


          -if game_ship.orientation == "horizontal"
            -if game_ship.sunk
              -color = "#ff0000"

            =game_ship.ship.name
            %span
              .game_ships_horizontal{:id => "game_ship_#{game_ship.id}",:style => "width: #{game_ship.ship.length * 30}px;background-color: #{color}", :game_id => game.id, :orientation => "horizontal"}
                &nbsp;

#nuke_data{:style => "display:none"}
  #server_nuke_ids
    -server_nuke_ids = []
    -Nuke.where(:game_id =>game.id, :server_nuke_boolean => true ).each do |nuke|
      - server_nuke_ids << nuke.id
    =server_nuke_ids.join(",")
  #server_x
    -server_x = []
    -Nuke.where(:game_id =>game.id, :server_nuke_boolean => true ).each do |nuke|
      - server_x << nuke.x
    =server_x.join(",")
  #server_y
    -server_y = []
    -Nuke.where(:game_id =>game.id, :server_nuke_boolean => true ).each do |nuke|
      - server_y << nuke.y
    =server_y.join(",")
  #server_hit_miss
    -server_hit_miss = []
    -Nuke.where(:game_id =>game.id, :server_nuke_boolean => true ).each do |nuke|
      - server_hit_miss << nuke.status
    =server_hit_miss.join(",")

  #nuke_ids
    -nuke_ids = []
    -Nuke.where(:game_id =>game.id, :server_nuke_boolean => false ).each do |nuke|
      - nuke_ids << nuke.id
    =nuke_ids.join(",")
  #nuke_x
    -nuke_x = []
    -Nuke.where(:game_id =>game.id, :server_nuke_boolean => false ).each do |nuke|
      - nuke_x << nuke.x
    =nuke_x.join(",")
  #nuke_y
    -nuke_y = []
    -Nuke.where(:game_id =>game.id, :server_nuke_boolean => false ).each do |nuke|
      - nuke_y << nuke.y
    =nuke_y.join(",")
  #nuke_hit_miss
    -nuke_hit_miss = []
    -Nuke.where(:game_id =>game.id, :server_nuke_boolean => false ).each do |nuke|
      - nuke_hit_miss << nuke.status
    =nuke_hit_miss.join(",")


#javascript_data{:style => "display:none"}
  #game_ship_ids
    -game_ship_ids = []
    -GameShip.where(:game_id =>game.id ).each do |game_ship|
      - game_ship_ids << game_ship.id
    =game_ship_ids.join(",")

  #game_ship_x
    -game_ship_x = []
    -GameShip.where(:game_id =>game.id ).each do |game_ship|
      - game_ship_x << game_ship.x
    =game_ship_x.join(",")
  #game_ship_y
    -game_ship_y = []
    -GameShip.where(:game_id =>game.id ).each do |game_ship|
      - game_ship_y << game_ship.y
    =game_ship_y.join(",")

  #game_ship_length
    -game_ship_length = []
    -GameShip.where(:game_id =>game.id ).each do |game_ship|
      - game_ship_length << game_ship.ship.length
    =game_ship_length.join(",")
  #game_ship_orientation
    -game_ship_orientation = []
    -GameShip.where(:game_id =>game.id ).each do |game_ship|
      - game_ship_orientation << game_ship.orientation
    =game_ship_orientation.join(",")
:javascript
  $(function() {
    nuke_server();
    draw_ships_for_game();
    draw_nukes_for_game();
  });

app/views/games/_form.html.haml
= semantic_form_for @game do |f|
  -if @game.errors.any?
    #error_explanation
      %strong= "#{pluralize(@game.errors.count, "error")} prohibited this game from being saved:"
      %ol
        - @game.errors.full_messages.each do |msg|
          %li= msg
  =f.hidden_field :client_hits, :value => 0
  =f.hidden_field :server_hits, :value => 0
  =f.inputs "Details" do
    =f.label :name
    %br
    = f.text_field :name
    %br
    = f.label :email
    %br
    = f.text_field :email

  = f.submit "Create Game"

app/views/games/_index.html.haml
%p
  = link_to 'New Game', new_game_path
  |
  = link_to "Back", :back
-if !games.empty?
  %h1 Listing games
  %table.dataTable
    %tr
      %th
      %th


    - games.each do |game|
      %tr

        %td= link_to 'Edit', edit_game_path(game)
        %td= link_to 'Destroy', game, :confirm => 'Are you sure?', :method => :delete

%br


app/views/games/_lost_game.html.haml
%h1 You Have lost against the server please try again

app/views/games/_won_game.html.haml
%h1 You Have won the server

app/views/games/battle.html.haml
%h2 Game
.enemy
  %div{:style => "width: 125px;"}
    %h3= "Enemy's Seas"
  %table.enemy_board

    %tr.align_center
      %td.white
      -10.times do |g|
        %td.white
          ="#{g}"
    -10.times do |i|
      %tr.line_one
        %td.white
          ="#{i}"
        -Block.where(:game_id => @game.id, :server_board => true, :y => i).order(:x).each do |block|
          %td.attack_area{:id => "enemy_board_#{block.x}_#{block.y}", :data_x => block.x, :data_y => block.y, :data_game_id => @game.id}

.player
  %div{:style => "width: 125px;"}
    %h3= "Player "

  %table.player_board
    %tr.align_center
      %td.white
      -10.times do |g|
        %td.white
          ="#{g}"
    -10.times do |i|
      %tr.line_one
        %td.white
          ="#{i}"
        -Block.where(:game_id => @game.id, :server_board => false, :y => i).order(:x).each do |block|

          %td.player_placement{:id => "player_board_#{block.x}_#{block.y}", :data_x => block.x, :data_y => block.y}

  .enemy_sunk_ships
    %h3
      ="Server Ships that have been sunk:"
    
    -ServerShip.where(:game_id => @game.id, :sunk=> true).each do |server_ship|
      =server_ship.name
      %br
.ships_show
  %h3 Player Ships
  %table
    %tr
      %th

      %th
    %tr
      %td
        -GameShip.where(:game_id => @game.id).order(:ship_id).each do |game_ship|
          -color = "#6d6969"

          -if game_ship.orientation == "vertical"
            -if game_ship.sunk
              -color = "#ff0000"

            =game_ship.ship.name
            %span
              .game_ships_vertical{:id => "game_ship_#{game_ship.id}",:style => "height: #{game_ship.ship.length * 30}px;background-color: #{color}", :game_id => @game.id, :orientation => "vertical"}
                &nbsp;
      %td
        -GameShip.where(:game_id => @game.id).order(:ship_id).each do |game_ship|
          -color = "#6d6969"


          -if game_ship.orientation == "horizontal"
            -if game_ship.sunk
              -color = "#ff0000"

            =game_ship.ship.name
            %span
              .game_ships_horizontal{:id => "game_ship_#{game_ship.id}",:style => "width: #{game_ship.ship.length * 30}px;background-color: #{color}", :game_id => @game.id, :orientation => "horizontal"}
                &nbsp;

#nuke_data{:style => "display:none"}
  #server_nuke_ids
    -server_nuke_ids = []
    -Nuke.where(:game_id =>@game.id, :server_nuke_boolean => true ).each do |nuke|
      - server_nuke_ids << nuke.id
    =server_nuke_ids.join(",")
  #server_x
    -server_x = []
    -Nuke.where(:game_id =>@game.id, :server_nuke_boolean => true ).each do |nuke|
      - server_x << nuke.x
    =server_x.join(",")
  #server_y
    -server_y = []
    -Nuke.where(:game_id =>@game.id, :server_nuke_boolean => true ).each do |nuke|
      - server_y << nuke.y
    =server_y.join(",")
  #server_hit_miss
    -server_hit_miss = []
    -Nuke.where(:game_id =>@game.id, :server_nuke_boolean => true ).each do |nuke|
      - server_hit_miss << nuke.status
    =server_hit_miss.join(",")

  #nuke_ids
    -nuke_ids = []
    -Nuke.where(:game_id =>@game.id, :server_nuke_boolean => false ).each do |nuke|
      - nuke_ids << nuke.id
    =nuke_ids.join(",")
  #nuke_x
    -nuke_x = []
    -Nuke.where(:game_id =>@game.id, :server_nuke_boolean => false ).each do |nuke|
      - nuke_x << nuke.x
    =nuke_x.join(",")
  #nuke_y
    -nuke_y = []
    -Nuke.where(:game_id =>@game.id, :server_nuke_boolean => false ).each do |nuke|
      - nuke_y << nuke.y
    =nuke_y.join(",")
  #nuke_hit_miss
    -nuke_hit_miss = []
    -Nuke.where(:game_id =>@game.id, :server_nuke_boolean => false ).each do |nuke|
      - nuke_hit_miss << nuke.status
    =nuke_hit_miss.join(",")


#javascript_data{:style => "display:none"}
  #game_ship_ids
    -game_ship_ids = []
    -GameShip.where(:game_id =>@game.id ).each do |game_ship|
      - game_ship_ids << game_ship.id
    =game_ship_ids.join(",")

  #game_ship_x
    -game_ship_x = []
    -GameShip.where(:game_id =>@game.id ).each do |game_ship|
      - game_ship_x << game_ship.x
    =game_ship_x.join(",")
  #game_ship_y
    -game_ship_y = []
    -GameShip.where(:game_id =>@game.id ).each do |game_ship|
      - game_ship_y << game_ship.y
    =game_ship_y.join(",")

  #game_ship_length
    -game_ship_length = []
    -GameShip.where(:game_id =>@game.id ).each do |game_ship|
      - game_ship_length << game_ship.ship.length
    =game_ship_length.join(",")
  #game_ship_orientation
    -game_ship_orientation = []
    -GameShip.where(:game_id =>@game.id ).each do |game_ship|
      - game_ship_orientation << game_ship.orientation
    =game_ship_orientation.join(",")
:javascript
  $(function() {
    nuke_server();
    draw_ships_for_game();
    draw_nukes_for_game();
  });

app/views/games/edit.html.haml
%h1 Editing game
%p
  = link_to 'Back', :back

= render 'form'

app/views/games/index.html.haml
%h1 Listing games
%p
  = link_to 'New Game', new_game_path
  |
  = link_to "Back", :back
-if !@games.empty?
  %table.dataTable
    %tr
      %th User Name
      %th User Email
      %th
      %th


    - @games.each do |game|
      %tr
        %td= game.name
        %td= game.email
        %td= link_to 'Edit', edit_game_path(game)
        %td= link_to 'Destroy', game, :confirm => 'Are you sure?', :method => :delete
        %td= link_to 'Show', battle_game_path(game)
%br

app/views/games/new.html.haml
%h1 New game
%p
  = link_to 'Back', :back

= render 'form'

app/views/games/register.erb
<%=@json_string %>

app/views/games/show.html.haml
-if @game.errors.any?
  #error_explanation
    %strong= "#{pluralize(@game.errors.count, "error")} prohibited this game from being saved:"
    %ol
      - @game.errors.full_messages.each do |msg|
        %li= msg


%h3= "Game Board"
%table
  %tr
    %td
      %table.player_board
        %tr.align_center
          %td.white
          -10.times do |g|
            %td.white
              ="#{g}"
        -10.times do |i|
          %tr.line_one
            %td.white
              ="#{i}"
            -Block.where(:game_id => @game.id, :server_board => false, :y => i).order(:x).each do |block|

              %td.player_placement{:id => "player_board_#{block.x}_#{block.y}", :data_x => block.x, :data_y => block.y}
                = "#{block.x}:#{block.y}"


    %td      
      #ships_for_game
        %h3 Ship Details
        %table
          %tr
            %td

              #ships_horizontal
                %h4
                  ="Orientation : Horizontal"
                %table
                  %tr


                    %td

                    -Ship.all.each do |ship|
                      %tr
                        -total_ships_game = GameShip.where(:ship_id => ship.id, :game_id => @game.id).count
                        -if total_ships_game < ship.max_per_game
                          %td
                            =ship.name

                          -(ship.max_per_game - total_ships_game).times do |i|
                            %td
                              -if ship.length > 2
                                .ships_horizontal{:id => "ship_#{ship.id}",:style => "width: #{(ship.length * 30) + 15}px;", :ship_id =>ship.id, :orientation => "horizontal", :data_length => ship.length, :game_id => @game.id}
                                  &nbsp;
                              -else
                                .ships_horizontal{:id => "ship_#{ship.id}",:style => "width: #{(ship.length * 30)}px;", :ship_id =>ship.id, :orientation => "horizontal", :data_length => ship.length, :game_id => @game.id}
                                  &nbsp;
            %td

              #ships_vertical
                %h4
                  ="Orientation : Vertical"
                %table
                  %tr

                    -Ship.all.each do |ship|
                      %td
                        -total_ships_game = GameShip.where(:ship_id => ship.id, :game_id => @game.id).count
                        -if total_ships_game < ship.max_per_game
                          %span
                            =ship.name

                          -(ship.max_per_game - total_ships_game).times do |i|
                            %span
                              .ships_vertical{:id => "ship_#{ship.id}",:style => "height: #{(ship.length * 30)}px;", :ship_id =>ship.id, :orientation => "vertical", :data_length => ship.length, :game_id => @game.id }
                                &nbsp;
                              %br
      :javascript
        $(function() {
          ShipsDraggables();
          ShipsDroppables();
          draw_ships_for_game();
        });
      %br
%span=link_to "Register Game on Server", register_game_path(@game)        
%h3
  Ships In Play
%table.game_ships{:border => 0, :cellpadding => 0, :cellspacing => 0}
  %tr
    %th
      Ship Name
    %th
      x coordinates
    %th
      y coordinates
    %th
      Length
    %th
      Edit
    %th
      Remove
  -GameShip.where(:game_id => @game.id).order(:x).each do |game_ship|
    %tr
      %td
        =game_ship.ship.name
      %td
        =game_ship.x
      %td
        =game_ship.y
      %td
        =game_ship.ship.length
      %td
        =link_to "Move Ship", edit_game_ship_path(:id => game_ship.id), :remote => true
      %td
        =link_to "Delete Ship", game_ship_path(:id => game_ship.id), :method => :delete, :remote => true



#json_string{:style => "display:none"}
  =@game.json_string




#javascript_data{:style => "display:none"}
  #game_ship_ids
    -game_ship_ids = []
    -GameShip.where(:game_id =>@game.id ).each do |game_ship|
      - game_ship_ids << game_ship.id
    =game_ship_ids.join(",")

  #game_ship_x
    -game_ship_x = []
    -GameShip.where(:game_id =>@game.id ).each do |game_ship|
      - game_ship_x << game_ship.x
    =game_ship_x.join(",")
  #game_ship_y
    -game_ship_y = []
    -GameShip.where(:game_id =>@game.id ).each do |game_ship|
      - game_ship_y << game_ship.y
    =game_ship_y.join(",")

  #game_ship_length
    -game_ship_length = []
    -GameShip.where(:game_id =>@game.id ).each do |game_ship|
      - game_ship_length << game_ship.ship.length
    =game_ship_length.join(",")
  #game_ship_orientation
    -game_ship_orientation = []
    -GameShip.where(:game_id =>@game.id ).each do |game_ship|
      - game_ship_orientation << game_ship.orientation
    =game_ship_orientation.join(",")