config/routes.rb
Battleships::Application.routes.draw do
  resources :blocks

  resources :game_ships

  resources :nukes

  resources :ships

  resources :games do
    get :register, :on => :member
    post :nuke, :on => :member
    get :battle, :on => :member
  end

  root :to => "public#home"
end

app/views/layouts/_lightbox_small.html.haml
#lightbox_small{:style => "display:none"}
  #lightbox_top_div
    %table{:width=>"100%", :border=>"0", :cellpadding=>"0", :cellspacing=>"0", :class=>"work-panel"}
      %tr
        %td{:class=>"corner top-left-corner"}
        %td{:class=>"top"} &nbsp;
        %td{:class=>"corner top-right-corner-close"}
          #close_lightbox_small{:onclick =>"close_lightbox_small()"}
  #lightbox_content_small

  #lightbox_bottom_div
    %table{:width=>"100%", :border=>"0", :cellpadding=>"0", :cellspacing=>"0", :class=>"work-panel"}
      %tr
        %td{:class=>"corner bottom-left-corner"}
        %td{:class=>"bottom"} &nbsp;
        %td{:class=>"corner bottom-right-corner"}

app/views/layouts/_navigation_links.html.haml

%div{:id=>"navigation",:class=>"navigation"}
  %ul
    %li
      = link_to "Games", games_path()
      ="|"
      = link_to "Ships", ships_path()


app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Battleships
    = stylesheet_link_tag 'application'
    = javascript_include_tag  "application"
    = csrf_meta_tag
  %body
    #access_keys
      .acc_content
        = render :partial=>"/layouts/navigation_links"
        %h1 Battleships
    #work-area
      %table#main-panel{:class=>"work-panel", :width=>"100%", :border=>"0", :cellpadding=>"2", :cellspacing=>"0"}
        %tr
          %td.top
        %tr
          %td{:class=>"panel-content"}
            %span.notice#flash_notice= notice
            %span.notice#flash_alert= alert
            .content#content
              = yield
        %tr
          %td{:class=>"bottom"}
    = render :partial=>"/layouts/lightbox_small"

